import tempfile
import unittest
from pathlib import Path
from eda_lab.models import JobSpec
from eda_lab.parser import parse_report
from eda_lab.service import JobService
from eda_lab.runner import SyntheticTimingAdapter
from eda_lab.store import Store

class Stage1Tests(unittest.TestCase):
    def test_parser_converts_ps_and_fails_negative_slack(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "report.txt"
            path.write_text("\n".join([
                "SYNTHETIC / NOT GENERATED BY AN EDA TOOL",
                "fixture_format_version=1", "run_id=r1", "stage=timing",
                "corner=SS_0C", "tool_exit_code=0", "worst_slack=-80 ps", "",
            ]), encoding="utf-8")
            result = parse_report(path)
            self.assertEqual(result.parse_status, "OK")
            self.assertEqual(result.check_status, "FAIL")
            self.assertEqual(result.metrics["worst_slack_ns"], -0.08)

    def test_fixture_profiles_cover_missing_data_and_transport_failures(self):
        spec = JobSpec("fixture", "design-a", "PCIe", "synthetic-timing", "TT_25C", 0.12, "ns")
        with self.assertRaises(TimeoutError):
            SyntheticTimingAdapter("timeout").run(spec)
        with self.assertRaises(ConnectionError):
            SyntheticTimingAdapter("communication_error").run(spec)
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "missing.report"
            path.write_text("\n".join([
                "SYNTHETIC / NOT GENERATED BY AN EDA TOOL",
                "fixture_format_version=1", "run_id=fixture", "stage=timing",
                "corner=TT_25C", "tool_exit_code=0", "",
            ]), encoding="utf-8")
            result = parse_report(path)
            self.assertEqual(result.parse_status, "INVALID")

    def test_retry_records_attempts_and_exhausts_retryable_errors(self):
        spec = JobSpec("retry", "design-a", "PCIe", "synthetic-timing", "TT_25C", 0.12, "ns")
        service = JobService(Store(), max_workers=1, max_attempts=2, adapter=SyntheticTimingAdapter("timeout"))
        service.submit(spec)
        service.futures["retry"].result(timeout=2)
        result = service.get("retry")
        self.assertEqual(result["status"], "FAILED")
        self.assertEqual(len(result["attempts"]), 2)
        self.assertEqual(result["attempts"][-1]["error_type"], "timeout")

    def test_bounded_batch_completes_with_worker_limit(self):
        service = JobService(Store(), max_workers=4)
        specs = [JobSpec(f"batch-{i}", "design-a", "PCIe", "synthetic-timing", "TT_25C", 0.12, "ns", 0.005) for i in range(20)]
        for spec in specs:
            service.submit(spec)
        for spec in specs:
            service.futures[spec.job_id].result(timeout=3)
        results = [service.get(spec.job_id) for spec in specs]
        self.assertTrue(all(result["status"] == "SUCCEEDED" for result in results))
        self.assertEqual(len({result["job_id"] for result in results}), 20)

    def test_service_runs_end_to_end_and_is_idempotent(self):
        service = JobService(Store(), max_workers=2)
        spec = JobSpec("r2", "design-a", "PCIe", "synthetic-timing", "TT_25C", 0.12, "ns")
        first = service.submit(spec)
        second = service.submit(spec)
        self.assertEqual(first["job_id"], second["job_id"])
        service.futures["r2"].result(timeout=2)
        result = service.get("r2")
        self.assertEqual(result["status"], "SUCCEEDED")
        self.assertEqual(result["check_status"], "PASS")

if __name__ == "__main__":
    unittest.main()
