/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module tiny(clk, a, b, y);
  input clk;
  wire clk;
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  wire _0_;
  wire q;
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(q),
    .B(b),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(_0_),
    .Q(y)
  );
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(clk),
    .D(a),
    .Q(q)
  );
endmodule
