"""Observe a synthetic parser/service boundary after a human prediction record.

No product state changes: temporary reports, in-memory DB, stdout JSON only.
This is not a real EDA tool run or an acceptance-test replacement.
"""
import argparse
import hashlib
import json
import sys
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from types import SimpleNamespace

CASES = {
    "nonzero_negative": (1, "-0.12 ns"),
    "nonzero_missing": (1, None),
    "zero_positive": (0, "0.12 ns"),
}
STATUS_FIELDS = ("parse_status", "check_status", "run_status", "attempt_status")


def load_prediction(path):
    record = json.loads(path.read_text(encoding="utf-8"))
    for field in ("problem", "constraint", "invariant", "acceptance", "failure",
                  "decision", "decision_reason"):
        if not isinstance(record.get(field), str) or not record[field].strip():
            raise ValueError(f"Human record required: {field}")
    stamp = datetime.fromisoformat(record["recorded_at"].replace("Z", "+00:00"))
    if stamp.tzinfo is None or stamp > datetime.now(timezone.utc):
        raise ValueError("recorded_at must be timezone-aware and not in the future")
    for name in CASES:
        prediction = record["predictions"][name]
        for field in (*STATUS_FIELDS, "reason"):
            if not isinstance(prediction.get(field), str) or not prediction[field].strip():
                raise ValueError(f"Human prediction required: {name}.{field}")
    return record


def observe(name, exit_code, slack, directory):
    # Delayed imports keep --help and record validation independent of execution.
    from eda_lab.models import JobSpec
    from eda_lab.parser import parse_report
    from eda_lab.service import JobService
    from eda_lab.store import Store

    lines = ["SYNTHETIC / NOT GENERATED BY AN EDA TOOL",
             "fixture_format_version=1", f"run_id={name}", "stage=timing",
             "corner=TT", f"tool_exit_code={exit_code}"]
    if slack is not None:
        lines.append(f"worst_slack={slack}")
    source = "\n".join(lines) + "\n"
    path = directory / f"{name}.report"
    path.write_text(source, encoding="utf-8")
    store = Store()
    service = JobService(store, max_workers=1, max_attempts=1,
                         adapter=SimpleNamespace(run=lambda spec: path))
    start = time.perf_counter()
    try:
        parsed = parse_report(path)
        spec = JobSpec(name, "synthetic-design", "synthetic", "synthetic-timing",
                       "TT", 0.12, "ns", 0)
        service.submit(spec)
        service.futures[name].result(timeout=5)
        run = service.get(name)
        observed = {
            "parse_status": parsed.parse_status,
            "check_status": parsed.check_status,
            "run_status": run["status"],
            "attempt_status": run["attempts"][-1]["status"],
        }
        # Temporary paths are not durable evidence; preserve source bytes/hash.
        run.pop("artifact_path", None)
        for attempt in run["attempts"]:
            attempt.pop("artifact_path", None)
        return {
            "case": name, "source_kind": "synthetic", "input": source,
            "input_sha256": hashlib.sha256(source.encode()).hexdigest(),
            "tool_exit_code": exit_code, "observed": observed,
            "parser_metrics": parsed.metrics, "parser_errors": parsed.errors,
            "stored_run": run, "elapsed_ms": (time.perf_counter() - start) * 1000,
            "false_run_success": exit_code != 0 and run["status"] == "SUCCEEDED",
            "false_attempt_success": exit_code != 0 and any(
                a["status"] == "SUCCEEDED" for a in run["attempts"]),
        }
    finally:
        service.executor.shutdown(wait=True)
        store.connection.close()


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument("--prediction-file", type=Path, required=True,
                     help="Human-authored JSON; see exit_status_prediction.example.json")
    args = cli.parse_args()
    try:
        record = load_prediction(args.prediction_file)
        root = Path(__file__).resolve().parents[1]
        hashes = {
            str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in [Path(__file__).resolve(), *sorted((root / "src/eda_lab").glob("*.py"))]
        }
        started = datetime.now(timezone.utc).isoformat()
        with tempfile.TemporaryDirectory(prefix="eda-status-probe-") as directory:
            rows = [observe(name, code, slack, Path(directory))
                    for name, (code, slack) in CASES.items()]
        for row in rows:
            expected = record["predictions"][row["case"]]
            row["prediction_matches"] = {
                key: expected[key] == value for key, value in row["observed"].items()
            }
        failures = sum(r["false_run_success"] or r["false_attempt_success"] for r in rows)
        print(json.dumps({
            "protocol": "synthetic-exit-status-probe-v1",
            "human_record": record,
            "human_authorship_verified": False,
            "started_at": started, "code_sha256": hashes, "rows": rows,
            "nonzero_case_count": sum(code != 0 for code, _ in CASES.values()),
            "false_success_case_count": failures,
            "acceptance": "Human Evidence Gate pending; zero count alone is not acceptance",
            "limits": "Synthetic only; no tool/version, retry, API or performance validation",
        }, ensure_ascii=False, indent=2, allow_nan=False))
        return 1 if failures else 0
    except Exception as exc:
        print(json.dumps({"experiment_error": type(exc).__name__, "message": str(exc)},
                         ensure_ascii=False), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
