import hashlib
import re
from pathlib import Path
from .models import ParseResult

REQUIRED = ("fixture_format_version", "run_id", "stage", "corner", "tool_exit_code", "worst_slack")

def parse_report(path: str | Path) -> ParseResult:
    source = Path(path)
    lines = source.read_text(encoding="utf-8").splitlines()
    values: dict[str, str] = {}
    errors: list[str] = []
    if not lines or lines[0].strip() != "SYNTHETIC / NOT GENERATED BY AN EDA TOOL":
        errors.append("missing synthetic marker")
    for number, line in enumerate(lines, 1):
        if "=" not in line or line.startswith("SYNTHETIC"):
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key in values:
            errors.append(f"duplicate field {key} at line {number}")
        values[key] = value
    for key in REQUIRED:
        if key not in values:
            errors.append(f"missing field {key}")
    if errors:
        return ParseResult("INVALID", "UNKNOWN", {}, errors)
    try:
        version = int(values["fixture_format_version"])
        if version != 1:
            raise ValueError("unsupported fixture version")
        exit_code = int(values["tool_exit_code"])
        match = re.fullmatch(r"(-?\d+(?:\.\d+)?)\s*(ns|ps)", values["worst_slack"])
        if not match:
            raise ValueError("unsupported slack format or unit")
        numeric = float(match.group(1))
        unit = match.group(2)
        slack_ns = numeric if unit == "ns" else numeric / 1000.0
    except ValueError as exc:
        return ParseResult("INVALID", "UNKNOWN", {}, [str(exc)])
    metrics = {
        "source_kind": "synthetic",
        "fixture_format_version": version,
        "run_id": values["run_id"],
        "stage": values["stage"],
        "corner": values["corner"],
        "tool_exit_code": exit_code,
        "worst_slack_ns": slack_ns,
        "original_value": numeric,
        "original_unit": unit,
        "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
    }
    job_status = "SUCCEEDED" if exit_code == 0 else "FAILED"
    check_status = "PASS" if slack_ns >= 0 else "FAIL"
    metrics["job_status"] = job_status
    return ParseResult("OK", check_status, metrics, [])
