import hashlib
import math
import re
from pathlib import Path

from .models import ParseResult

SYNTHETIC_MARKER = "SYNTHETIC / NOT GENERATED BY AN EDA TOOL"
OPENSTA_COMPLETION_MARKER = "EDA_LAB_REPORT_END"
SYNTHETIC_REQUIRED = (
    "fixture_format_version",
    "run_id",
    "stage",
    "corner",
    "tool_exit_code",
    "worst_slack",
)
NUMBER = r"[-+]?\d+(?:\.\d+)?"


def _provenance(source_kind: str, source_sha256: str, parser: str, **extra: object) -> dict[str, object]:
    return {
        "source_kind": source_kind,
        "source_sha256": source_sha256,
        "parser": parser,
        "artifact_kind": "timing_report",
        **extra,
    }


def _invalid(errors: list[str], source_kind: str, source_sha256: str, parser: str,
             **provenance_fields: object) -> ParseResult:
    return ParseResult(
        "INVALID",
        "UNKNOWN",
        {},
        errors,
        "incomplete",
        _provenance(source_kind, source_sha256, parser, **provenance_fields),
    )


def _read_report(path: str | Path) -> tuple[str, str]:
    payload = Path(path).read_bytes()
    return payload.decode("utf-8"), hashlib.sha256(payload).hexdigest()


def _synthetic_finish(values: dict[str, str], errors: list[str], source_sha256: str) -> ParseResult:
    provenance = _provenance("synthetic", source_sha256, "eda_lab.synthetic:v1")
    for key in SYNTHETIC_REQUIRED:
        if key not in values:
            errors.append(f"missing field {key}")
    if errors:
        return ParseResult("INVALID", "UNKNOWN", {}, errors, "incomplete", provenance)
    try:
        version = int(values["fixture_format_version"])
        if version != 1:
            raise ValueError("unsupported fixture version")
        exit_code = int(values["tool_exit_code"])
        match = re.fullmatch(rf"({NUMBER})\s*(ns|ps)", values["worst_slack"])
        if not match:
            raise ValueError("unsupported slack format or unit")
        numeric = float(match.group(1))
        if not math.isfinite(numeric):
            raise ValueError("non-finite slack")
        unit = match.group(2)
        slack_ns = numeric if unit == "ns" else numeric / 1000.0
    except ValueError as exc:
        return _invalid([str(exc)], "synthetic", source_sha256, "eda_lab.synthetic:v1")
    metrics = {
        "source_kind": "synthetic",
        "fixture_format_version": version,
        "run_id": values["run_id"],
        "stage": values["stage"],
        "corner": values["corner"],
        "tool_exit_code": exit_code,
        "worst_slack_ns": slack_ns,
        "original_value": numeric,
        "original_unit": unit,
        "source_sha256": source_sha256,
        "job_status": "SUCCEEDED" if exit_code == 0 else "FAILED",
    }
    provenance = {
        **provenance,
        "tool_exit_code": exit_code,
        "flow_name": values["stage"],
        "corner": values["corner"],
        "run_id": values["run_id"],
    }
    return ParseResult("OK", "PASS" if slack_ns >= 0 else "FAIL", metrics, [], "complete", provenance)


def _parse_synthetic(text: str, source_sha256: str) -> ParseResult:
    values: dict[str, str] = {}
    errors: list[str] = []
    for line_count, line in enumerate(text.splitlines(), start=1):
        if "=" not in line or line.startswith(SYNTHETIC_MARKER):
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        if key in values:
            errors.append(f"duplicate field {key} at line {line_count}")
        values[key] = value
    return _synthetic_finish(values, errors, source_sha256)


def _single_match(pattern: str, text: str, field: str, errors: list[str]) -> re.Match[str] | None:
    matches = list(re.finditer(pattern, text, re.MULTILINE))
    if len(matches) != 1:
        errors.append(f"expected exactly one {field}, found {len(matches)}")
        return None
    return matches[0]


def _parse_opensta_setup_max(text: str, source_sha256: str) -> ParseResult:
    parser_name = "eda_lab.opensta_setup_max:v1"
    errors: list[str] = []
    banner = _single_match(r"^OpenSTA\s+(\S+)\s+([0-9a-f]+)\s+Copyright", text, "OpenSTA banner", errors)
    if banner and banner.group(1) != "3.1.0":
        errors.append(f"unsupported OpenSTA version {banner.group(1)}")
    if text.count(OPENSTA_COMPLETION_MARKER) != 1:
        errors.append("missing or duplicate OpenSTA completion marker")
    if re.search(r"(?im)^error(?:\s|:)", text):
        errors.append("OpenSTA error diagnostic present")
    unit = _single_match(r"^\s*time\s+(\S+)\s*$", text, "time unit", errors)
    if unit and unit.group(1) != "1ns":
        errors.append(f"unsupported time unit {unit.group(1)}")
    startpoint = _single_match(r"^Startpoint:\s+(.+?)\s+\(", text, "startpoint", errors)
    endpoint = _single_match(r"^Endpoint:\s+(.+?)\s+\(", text, "endpoint", errors)
    path_group = _single_match(r"^Path Group:\s+(\S+)\s*$", text, "path group", errors)
    path_type = _single_match(r"^Path Type:\s+(\S+)\s*$", text, "path type", errors)
    if path_type and path_type.group(1) != "max":
        errors.append(f"unsupported path type {path_type.group(1)}")
    summary = _single_match(
        rf"^-+\n"
        rf"\s*({NUMBER})\s+data required time\n"
        rf"\s*({NUMBER})\s+data arrival time\n"
        rf"-+\n"
        rf"\s*({NUMBER})\s+slack \((MET|VIOLATED)\)\s*$",
        text,
        "OpenSTA setup summary",
        errors,
    )
    worst = _single_match(rf"^worst slack max\s+({NUMBER})\s*$", text, "worst slack", errors)
    arrival_rows = list(re.finditer(rf"^\s*({NUMBER})\s+data arrival time\s*$", text, re.MULTILINE))
    if len(arrival_rows) != 2:
        errors.append(f"expected exactly two data arrival summaries, found {len(arrival_rows)}")
    if errors:
        return _invalid(errors, "tool_generated", source_sha256, parser_name)

    required_ns = float(summary.group(1))
    signed_arrival_ns = float(summary.group(2))
    slack_ns = float(summary.group(3))
    arrival_ns = float(arrival_rows[0].group(1))
    worst_slack_ns = float(worst.group(1))
    status_label = summary.group(4)
    values = (required_ns, signed_arrival_ns, arrival_ns, slack_ns, worst_slack_ns)
    if not all(math.isfinite(value) for value in values):
        return _invalid(["non-finite OpenSTA timing value"], "tool_generated", source_sha256, parser_name)
    if abs((required_ns + signed_arrival_ns) - slack_ns) > 0.000002:
        return _invalid(["OpenSTA setup arithmetic mismatch"], "tool_generated", source_sha256, parser_name)
    if abs(signed_arrival_ns + arrival_ns) > 0.000002:
        return _invalid(["OpenSTA arrival summary mismatch"], "tool_generated", source_sha256, parser_name)
    if abs(worst_slack_ns - slack_ns) > 0.0000005:
        return _invalid(["reported path slack differs from worst slack"], "tool_generated", source_sha256, parser_name)
    if (status_label == "MET" and slack_ns < 0) or (status_label == "VIOLATED" and slack_ns >= 0):
        return _invalid(["OpenSTA slack label contradicts slack sign"], "tool_generated", source_sha256, parser_name)

    tool_version, tool_revision = banner.group(1), banner.group(2)
    metrics = {
        "source_kind": "tool_generated",
        "tool_name": "OpenSTA",
        "tool_version": tool_version,
        "tool_revision": tool_revision,
        "analysis_type": "setup_max",
        "analysis_scope": "single_reported_path_group",
        "startpoint": startpoint.group(1),
        "endpoint": endpoint.group(1),
        "path_group": path_group.group(1),
        "arrival_time_ns": arrival_ns,
        "required_time_ns": required_ns,
        "reported_path_slack_ns": slack_ns,
        "worst_slack_ns": worst_slack_ns,
        "original_unit": "ns",
        "source_sha256": source_sha256,
    }
    provenance = _provenance(
        "tool_generated",
        source_sha256,
        parser_name,
        tool_name="OpenSTA",
        tool_version=tool_version,
        tool_revision=tool_revision,
        analysis_type="setup_max",
        report_profile="opensta-3.1.0-single-path-setup-max-v1",
    )
    return ParseResult(
        "OK",
        "PASS" if status_label == "MET" else "FAIL",
        metrics,
        [],
        "complete",
        provenance,
    )


def parse_report(path: str | Path) -> ParseResult:
    try:
        text, source_sha256 = _read_report(path)
    except UnicodeDecodeError:
        source = Path(path).read_bytes()
        return _invalid(
            ["report is not UTF-8"],
            "unknown",
            hashlib.sha256(source).hexdigest(),
            "eda_lab.dispatch:v1",
        )
    first_line = text.splitlines()[0].strip() if text.splitlines() else ""
    if first_line == SYNTHETIC_MARKER:
        return _parse_synthetic(text, source_sha256)
    if first_line.startswith("OpenSTA "):
        return _parse_opensta_setup_max(text, source_sha256)
    return _invalid(["unsupported timing report format"], "unknown", source_sha256, "eda_lab.dispatch:v1")


def parse_report_streaming(path: str | Path) -> ParseResult:
    """Compatibility entry point; parser behavior is identical for bounded local files."""
    return parse_report(path)
