import hashlib
import re
from pathlib import Path
from .models import ParseResult

REQUIRED = ("fixture_format_version", "run_id", "stage", "corner", "tool_exit_code", "worst_slack")


def _finish(values, errors, source_sha256):
    provenance = {
        "source_kind": "synthetic",
        "source_sha256": source_sha256,
        "parser": "eda_lab.parser:v1",
        "artifact_kind": "timing_report",
    }
    for key in REQUIRED:
        if key not in values:
            errors.append(f"missing field {key}")
    if errors:
        return ParseResult("INVALID", "UNKNOWN", {}, errors, "incomplete", provenance)
    try:
        version = int(values["fixture_format_version"])
        if version != 1:
            raise ValueError("unsupported fixture version")
        exit_code = int(values["tool_exit_code"])
        match = re.fullmatch(r"(-?\d+(?:\.\d+)?)\s*(ns|ps)", values["worst_slack"])
        if not match:
            raise ValueError("unsupported slack format or unit")
        numeric = float(match.group(1))
        unit = match.group(2)
        slack_ns = numeric if unit == "ns" else numeric / 1000.0
    except ValueError as exc:
        return ParseResult("INVALID", "UNKNOWN", {}, [str(exc)], "incomplete", provenance)
    metrics = {
        "source_kind": "synthetic",
        "fixture_format_version": version,
        "run_id": values["run_id"],
        "stage": values["stage"],
        "corner": values["corner"],
        "tool_exit_code": exit_code,
        "worst_slack_ns": slack_ns,
        "original_value": numeric,
        "original_unit": unit,
        "source_sha256": source_sha256,
        "job_status": "SUCCEEDED" if exit_code == 0 else "FAILED",
    }
    provenance = {
        **provenance,
        "tool_exit_code": exit_code,
        "flow_name": values["stage"],
        "corner": values["corner"],
        "run_id": values["run_id"],
    }
    return ParseResult("OK", "PASS" if slack_ns >= 0 else "FAIL", metrics, [], "complete", provenance)


def _consume(path: str | Path, streaming: bool) -> ParseResult:
    source = Path(path)
    values: dict[str, str] = {}
    errors: list[str] = []
    digest = hashlib.sha256()
    line_count = 0
    with source.open("rb") as handle:
        for raw in handle:
            line_count += 1
            digest.update(raw)
            line = raw.decode("utf-8").rstrip("\r\n")
            if line_count == 1 and line.strip() != "SYNTHETIC / NOT GENERATED BY AN EDA TOOL":
                errors.append("missing synthetic marker")
            if "=" not in line or line.startswith("SYNTHETIC"):
                continue
            key, value = line.split("=", 1)
            key, value = key.strip(), value.strip()
            if key in values:
                errors.append(f"duplicate field {key} at line {line_count}")
            values[key] = value
    return _finish(values, errors, digest.hexdigest())


def parse_report(path: str | Path) -> ParseResult:
    return _consume(path, streaming=False)


def parse_report_streaming(path: str | Path) -> ParseResult:
    """Parse one line at a time; fixture payloads remain synthetic and bounded by disk."""
    return _consume(path, streaming=True)
