import tempfile
import time
from pathlib import Path
from .models import AdapterRunResult, JobSpec


class SyntheticTimingAdapter:
    """EDA-like adapter with explicit fixture profiles; never represents real tool output."""

    def __init__(self, profile: str = "normal", artifact_bytes: int = 0):
        self.profile = profile
        self.artifact_bytes = artifact_bytes

    def run(self, spec: JobSpec) -> AdapterRunResult:
        if self.profile == "timeout":
            time.sleep(max(spec.duration_seconds, 0.01))
            raise TimeoutError("synthetic adapter timeout")
        if self.profile == "communication_error":
            raise ConnectionError("synthetic transport failure")

        time.sleep(spec.duration_seconds)
        directory = Path(tempfile.mkdtemp(prefix=f"eda-lab-{spec.job_id}-"))
        report = directory / "timing.report"
        fields = [
            "SYNTHETIC / NOT GENERATED BY AN EDA TOOL",
            "fixture_source=synthetic",
            "fixture_format_version=1",
            f"run_id={spec.job_id}",
            "stage=timing",
            f"corner={spec.corner}",
            "tool_exit_code=0",
            f"worst_slack={spec.worst_slack} {spec.unit}",
        ]
        if self.profile == "missing_worst_slack":
            fields = [line for line in fields if not line.startswith("worst_slack=")]
        elif self.profile == "malformed_unit":
            fields[-1] = f"worst_slack={spec.worst_slack} cycles"
        elif self.profile != "normal":
            raise ValueError(f"unknown synthetic fixture profile: {self.profile}")
        payload = "\n".join(fields) + "\n"
        if self.artifact_bytes > len(payload):
            payload += "# synthetic artifact padding\n" + "x" * (self.artifact_bytes - len(payload))
        report.write_text(payload, encoding="utf-8")
        return AdapterRunResult(report, process_exit_code=0)
