import os
import hashlib
import signal
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from threading import Lock
from .models import AdapterRunResult, JobSpec


class AdapterCancelledError(Exception):
    """The adapter observed an explicit cancellation of its child process."""


class SyntheticTimingAdapter:
    """EDA-like adapter with explicit fixture profiles; never represents real tool output."""

    def __init__(self, profile: str = "normal", artifact_bytes: int = 0):
        self.profile = profile
        self.artifact_bytes = artifact_bytes

    def run(self, spec: JobSpec) -> AdapterRunResult:
        if self.profile == "timeout":
            time.sleep(max(spec.duration_seconds, 0.01))
            raise TimeoutError("synthetic adapter timeout")
        if self.profile == "communication_error":
            raise ConnectionError("synthetic transport failure")

        time.sleep(spec.duration_seconds)
        directory = Path(tempfile.mkdtemp(prefix=f"eda-lab-{spec.job_id}-"))
        report = directory / "timing.report"
        fields = [
            "SYNTHETIC / NOT GENERATED BY AN EDA TOOL",
            "fixture_source=synthetic",
            "fixture_format_version=1",
            f"run_id={spec.job_id}",
            "stage=timing",
            f"corner={spec.corner}",
            "tool_exit_code=0",
            f"worst_slack={spec.worst_slack} {spec.unit}",
        ]
        if self.profile == "missing_worst_slack":
            fields = [line for line in fields if not line.startswith("worst_slack=")]
        elif self.profile == "malformed_unit":
            fields[-1] = f"worst_slack={spec.worst_slack} cycles"
        elif self.profile != "normal":
            raise ValueError(f"unknown synthetic fixture profile: {self.profile}")
        payload = "\n".join(fields) + "\n"
        if self.artifact_bytes > len(payload):
            payload += "# synthetic artifact padding\n" + "x" * (self.artifact_bytes - len(payload))
        report.write_text(payload, encoding="utf-8")
        return AdapterRunResult(report, process_exit_code=0)


class OpenStaSubprocessAdapter:
    """Run one fixed OpenSTA fixture as a separately observed child process."""

    def __init__(
        self,
        *,
        sta_path: Path,
        liberty_path: Path,
        fixture_dir: Path,
        sdc_name: str = "normal.sdc",
        script_name: str = "run.tcl",
        timeout_seconds: float = 30,
        termination_grace_seconds: float = 1,
    ):
        self.sta_path = Path(sta_path)
        self.liberty_path = Path(liberty_path)
        self.fixture_dir = Path(fixture_dir)
        self.sdc_name = sdc_name
        self.script_name = script_name
        self.timeout_seconds = timeout_seconds
        self.termination_grace_seconds = termination_grace_seconds
        self._processes: dict[str, subprocess.Popen] = {}
        self._cancelled_jobs: set[str] = set()
        self._lock = Lock()

    def cancel(self, job_id: str) -> bool:
        with self._lock:
            process = self._processes.get(job_id)
            if process is None or process.poll() is not None:
                return False
            self._cancelled_jobs.add(job_id)
            self._terminate_process_group(process, signal.SIGTERM)
            return True

    @staticmethod
    def _terminate_process_group(process: subprocess.Popen, sig: int) -> None:
        """Signal the dedicated session so adapter-created descendants cannot outlive an Attempt."""
        try:
            os.killpg(process.pid, sig)
        except ProcessLookupError:
            return

    def _required_fixture(self, name: str) -> Path:
        path = self.fixture_dir / name
        if not path.is_file():
            raise FileNotFoundError(f"required OpenSTA fixture is missing: {path}")
        return path

    @staticmethod
    def _sha256(path: Path) -> str:
        return hashlib.sha256(path.read_bytes()).hexdigest()

    def run(self, spec: JobSpec) -> AdapterRunResult:
        if not self.sta_path.is_file():
            raise FileNotFoundError(f"OpenSTA executable is missing: {self.sta_path}")
        if not self.liberty_path.is_file():
            raise FileNotFoundError(f"OpenSTA Liberty file is missing: {self.liberty_path}")

        script = self._required_fixture(self.script_name)
        sdc = self._required_fixture(self.sdc_name)
        netlist = self._required_fixture("tiny_mapped.v")
        directory = Path(tempfile.mkdtemp(prefix=f"eda-opensta-{spec.job_id}-"))
        for source in (script, sdc, netlist):
            shutil.copy2(source, directory / source.name)

        environment = os.environ.copy()
        environment.update({
            "EDA_LIB": str(self.liberty_path),
            "EDA_SDC": str(directory / sdc.name),
        })
        process = subprocess.Popen(
            [str(self.sta_path), "-no_init", "-exit", script.name],
            cwd=directory,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            start_new_session=True,
        )
        with self._lock:
            self._processes[spec.job_id] = process
        try:
            stdout, stderr = process.communicate(timeout=self.timeout_seconds)
        except subprocess.TimeoutExpired:
            self._terminate_process_group(process, signal.SIGTERM)
            termination = "SIGTERM"
            try:
                stdout, stderr = process.communicate(timeout=self.termination_grace_seconds)
            except subprocess.TimeoutExpired:
                self._terminate_process_group(process, signal.SIGKILL)
                stdout, stderr = process.communicate()
                termination = "SIGKILL"
            (directory / "timing.report").write_text(stdout or "", encoding="utf-8")
            (directory / "stderr.log").write_text(stderr or "", encoding="utf-8")
            raise TimeoutError(
                f"OpenSTA timed out after {self.timeout_seconds}s; pid={process.pid}; termination={termination}"
            )
        finally:
            with self._lock:
                self._processes.pop(spec.job_id, None)

        with self._lock:
            cancelled = spec.job_id in self._cancelled_jobs
            self._cancelled_jobs.discard(spec.job_id)
        if cancelled:
            (directory / "timing.report").write_text(stdout or "", encoding="utf-8")
            (directory / "stderr.log").write_text(stderr or "", encoding="utf-8")
            raise AdapterCancelledError(f"OpenSTA cancellation observed; pid={process.pid}")

        report = directory / "timing.report"
        report.write_text(stdout, encoding="utf-8")
        (directory / "stderr.log").write_text(stderr, encoding="utf-8")
        return AdapterRunResult(report, process_exit_code=process.returncode, execution_provenance={
            "command_template_id": "opensta-fixed-fixture-v1",
            "tool_path": str(self.sta_path),
            "liberty_sha256": self._sha256(self.liberty_path),
            "script_sha256": self._sha256(script),
            "sdc_sha256": self._sha256(sdc),
            "netlist_sha256": self._sha256(netlist),
        })
